config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :evaluations
    resources :organisations
    get 'resultats/:evaluation_id', to: "resultats#index", as: "resultats"
    get 'code_invitation', to: "invitation_code#index"
    post 'code_invitation', to: "invitation_code#join"
    get '/evaluations_builder/new', to: 'evaluations_builder#new'
    get '/evaluations_builder/:evaluation_id/:step', to: 'evaluations_builder#show', as: 'evaluation_builder'
    get '/', to: 'dashboard#index', as: ''
    post '/evaluations_builder/:evaluation_id/:step', to: 'evaluations_builder#update'
  end
  
  devise_for :users, path: '', path_names: { sign_in: "connexion", sign_out: "deconnexion", sign_up: "inscription", edit: "compte" }

  # get "entreprises", to: "organisations#public_list"
  get 'pilier-1', to: "statistiques#pillar1"
  get 'pilier-2', to: "statistiques#pillar2"
  get 'pilier-3', to: "statistiques#pillar3"
  get 'pilier-4', to: "statistiques#pillar4"
  get 'mentions-legales', to: "home#mentions_legales"
  get 'cgu', to: 'home#cgu'
  # get 'politique-de-confidentialite', to: 'home#politique'
  get 'contact', to: "contact#index"


  root "home#index"
end

app/views/evaluations_builder/informations.html.erb
<h1>
  <% if @evaluation.status != 'active' %>
    Nouvelle évaluation
  <% else %>
    Édition de l'évaluation de l'année <%= @evaluation.annee %>
  <% end %>
</h1>
<h2>Informations</h2>

<%= simple_form_for @evaluation, url: evaluation_builder_path, method: :post do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="row">
    <div class="col-md-4 mb-4">
      <%= f.input :annee %>
    </div>
    <div class="col-md-4 mb-4">
      <%= f.input :chiffre_affaires %>
    </div>
    <div class="col-md-4 mb-4">
      <%= f.input :resultat_net %>
    </div>
    <div class="col-md-4 mb-4">
      <%= f.input :nombre_salaries %>
    </div>
    <div class="col-md-4 mb-4">
      <%= f.input :nombre_salaries_etp %>
    </div>
  </div>
  <%= f.button :submit, 'Enregistrer', class: 'btn btn-primary' %>
<% end %>

app/views/evaluations_builder/pilier1.html.erb
<h1>
	<% if @evaluation.status != 'active' %>
		Nouvelle évaluation
	<% else %>
		Édition de l'évaluation de l'année <%= @evaluation.annee %>
	<% end %>
</h1>
<h2><span class="me-1 m-0">1.</span> Partage du pouvoir et des décisions</h2>

<%= simple_form_for @evaluation, url: evaluation_builder_path, method: :post do |f| %>
<%= render 'shared/error_messages', object: f.object %>
	<%= f.association :state do |il| %>

      <h3>Composition de la gouvernance</h3>

		<div class="row align-items-baseline my-5">
				<div class="col-md-4">
						<%= il.input :pouvoir_gouvernance_part_salaries_associes %>
				</div>
				<div class="col-md-4">
						<%= il.input :pouvoir_gouvernance_taux_societariat_femmes %>
				</div>
				<div class="col-md-4 ">
						<%= il.input :pouvoir_gouvernance_taux_droits_vote_salaries %>
				</div>
				<div class="col-md-4 ">
						<%= il.input :pouvoir_gouvernance_part_salaries_conseil %>
				</div>
				<div class="col-md-4 ">
						<%= il.input :pouvoir_gouvernance_part_femmes_conseil %>
				</div>
        <div class="col-12 col-sm-8">
          <%= il.input :pouvoir_gouvernance_diversite_categories, as: :check_boxes, collection: ['Salariés', 'Investisseurs', 'Fournisseurs', 'Sous-traitants', 'Clients', 'Experts', 'Syndicats', 'Pouvoirs publics', 'Associations', 'Grand public', 'Autres'], include_hidden: false %>
        </div>
		</div>

      <h3>Conditions du bon exercice de la démocratie</h3>

      <div class="row align-items-baseline my-5">
          <div class="col-md-4">
              <%= il.input :pouvoir_democratie_nombre_reunions %>
          </div>
          <div class="col-md-4">
              <%= il.input :pouvoir_democratie_taux_participation_formations %>
          </div>

		<div class="row align-items-baseline my-5">
				<div class="col-md-4 ">
						<%= il.input :pouvoir_democratie_nombre_reunions %>
				</div>
				<div class="col-md-4 ">
						<%= il.input :pouvoir_democratie_taux_participation_formations %>
				</div>

				<div class="col-md-4 ">
						<%= il.input :pouvoir_democratie_nombre_accords_signes %>
				</div>
				<div class="col-md-4 ">
						<%= il.input :pouvoir_democratie_accords_signes %>
				</div>
		</div>

      <div class="row align-items-baseline my-5">
          <div class="col-md-4">
              <%= il.input :pouvoir_strategique_taux_presence_assemblee %>
          </div>
          <div class="col-md-4">
              <%= il.input :pouvoir_strategique_implication_partage %>
          </div>
          <div class="col-md-4">
              <%= il.input :pouvoir_strategique_actifs_total %>
          </div>
        <div class="col-8 bg-primary rounded my-5" style="height: 6px"></div>
        <div class="col-md-8 estim"><%= il.input :pouvoir_estimation_realite %></div>
      </div>

		<div class="row align-items-baseline my-5">
				<div class="col-md-4 ">
						<%= il.input :pouvoir_strategique_taux_presence_assemblee %>
				</div>
				<div class="col-md-4 ">
						<%= il.input :pouvoir_strategique_implication_partage %>
				</div>
				<div class="col-md-4 ">
						<%= il.input :pouvoir_strategique_actifs_total %>
				</div>
		</div>

		<div class="col-md-4 "><%= il.input :pouvoir_estimation_realite %></div>

	<% end %>
</div>

	<div class="d-flex mt-5">
			<%= f.button :submit, "Enregister", class: 'btn btn-primary ms-auto d-flex mb-5' %>
	</div>
<% end %>

app/views/evaluations_builder/pilier4.html.erb
<h1>
  <% if @evaluation.status != 'active' %>
    Nouvelle évaluation
  <% else %>
    Édition de l'évaluation de l'année <%= @evaluation.annee %>
  <% end %>
</h1>

<h2><span class="me-1 m-0">4.</span>Impact environnemental, social et territorial</h2>


<%= simple_form_for @evaluation, url: evaluation_builder_path, method: :post do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.association :state do |il| %>

    <h3>Impact environnemental</h3>

    <div class="row align-items-start my-5">
      <div class="col-md-4 col-input">
      <%= il.input :impact_environnement_audit_impact, as: :radio_buttons %>
      </div>
      <div class="col-md-4 col-input">
      <%= il.input :impact_environnement_demarche_ecologique, as: :radio_buttons %>
      </div>
      <div class="col-md-4 col-input">
      <%= il.input :impact_environnement_discussion_impact, as: :radio_buttons %>
      </div>
    </div>

    <div class="row align-items-end my-5">
      <div class="col-md-4">
      <%= il.input :impact_environnement_part_energies_renouvelables %>
      </div>
      <div class="col-md-4">
      <%= il.input :impact_environnement_part_salaries_mobilite %>
      </div>
      <div class="col-md-4">
        <p>Calculez-vous le bilan carbone ?<p>
        <%= il.input :impact_environnement_bilan_carbone_scope_1 %>
        <%= il.input :impact_environnement_bilan_carbone_scope_2 %>
        <%= il.input :impact_environnement_bilan_carbone_scope_3 %>
      </div>
    </div>


    <h3>Impact social</h3>

    <div class="row align-items-baseline my-5">
      <div class="col-md-4">
        <%= il.input :impact_social_part_activite_structures_insertion %>
      </div>
      <div class="col-md-4">
        <%= il.input :impact_social_alternance_apprentissage %>
      </div>
      <div class="col-md-4">
        <%= il.input :impact_social_part_seniors %>
      </div>
      <div class="col-md-4">
        <%= il.input :impact_social_part_handicap %>
      </div>
    </div>

    <h3>Engagement en faveur de l'écosystème et du territoire</h3>

    <div class="row align-items-baseline my-5 col-input">
      <div class="col-md-4">
        <%= il.input :impact_engagement_part_resultat_missions_utiles %>
      </div>
      <div class="col-md-4">
        <%= il.input :impact_engagement_part_placements_responsables %>
      </div>
      <div class="col-md-4">
        <%= il.input :impact_engagement_part_impots_france %>
      </div>
      <div class="col-md-4">
        <%= il.input :impact_engagement_demarche_ethique_fournisseurs, as: :radio_buttons %>
      </div>
    </div>

    <div class="col-md-4">
    <%= il.input :impact_estimation_realite %>
    </div>
  <% end %>
</div>

</div>

  <div class="d-flex mt-5">
      <%= f.button :submit, "Enregistrer", class: 'btn btn-primary me-auto ms-auto d-flex mb-5 text-white' %>
  </div>
<% end %>

<script>
  function toggleRadio(event) {
    if(event.target.type === 'radio' && event.target.checked === true) {
      setTimeout(()=>{ event.target.checked = false; },0);
    }
  }
document.addEventListener('mouseup', toggleRadio);
</script>