config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :evaluations
    resources :organisations
    get 'resultats/:evaluation_id', to: "resultats#index", as: "resultats"
    get 'code_invitation', to: "invitation_code#index"
    post 'code_invitation', to: "invitation_code#join"
    get '/evaluations_builder/new', to: 'evaluations_builder#new'
    get '/evaluations_builder/:evaluation_id/:step', to: 'evaluations_builder#show', as: 'evaluation_builder'
    get '/', to: 'dashboard#index', as: ''
    post '/evaluations_builder/:evaluation_id/:step', to: 'evaluations_builder#update'
  end
  
  devise_for :users, path: '', path_names: { sign_in: "connexion", sign_out: "deconnexion", sign_up: "inscription", edit: "compte" }

  # get "entreprises", to: "organisations#public_list"
  get 'pilier-1', to: "statistiques#pillar1"
  get 'pilier-2', to: "statistiques#pillar2"
  get 'pilier-3', to: "statistiques#pillar3"
  get 'pilier-4', to: "statistiques#pillar4"
  get 'mentions-legales', to: "home#mentions_legales"
  get 'cgu', to: 'home#cgu'
  # get 'politique-de-confidentialite', to: 'home#politique'
  get 'contact', to: "contact#index"


  root "home#index"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    @organisation = current_user.organisation
  end
end

app/views/dashboard/index.html.erb
<h1>
  <% if @organisation.present? && @organisation.validation_admin %>
    <%= @organisation %>
  <% else %>
    Tableau de bord
  <% end %>
</h1>

<%= link_to 'Modifier', edit_organisation_path(@organisation), class: 'btn btn-primary mt-3' if @organisation.present? %>

<% if @organisation.nil? %>
  <div class="row">
    <%= link_to "Inscrire une organisation", new_organisation_path, class: "btn btn-primary" %>
    <div class="col mt-5">
      <div id="code_messages"></div>
      <%= form_with url: code_invitation_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :code, "Code d'invitation:" %>
          <%= f.text_field :code, class: "form-control" %>
        </div>
        <%= f.submit "Rejoindre une organisation", class: "btn btn-primary mt-3" %>
      <% end %>
    </div>
  </div>
<% else %>
  <% if @organisation.validation_admin %>
    <h2>Evaluations</h2>

    <ul class="list-group rounded my-5">
      <div class="list-group-item d-flex p-3">
        <div class="col">Année</div>
        <div class="row w-50 text-center">
          <div class="col">Pilier 1</div>
          <div class="col">Pilier 2</div>
          <div class="col">Pilier 3</div>
          <div class="col">Pilier 4</div>
        </div>
      </div>
      <% current_user.organisation.evaluations.active.each do |evaluation| %>
        <div class="list-group-item d-flex p-3">
          <div class="col">
            <%= link_to "Evaluation de l'année #{ evaluation.annee }", evaluation, class: "text-secondary fw-bold" %> |
            <%= link_to "Voir les résultats", resultats_path(evaluation_id: evaluation.id), class: "text-primary fw-bold" %> |
            <%= link_to "Éditer", admin_evaluation_builder_path(evaluation.id, 'informations'), class: "text-success fw-bold" %>
          </div>
          <div class="row w-50 text-center">
            <div class="col">10/10</div>
            <div class="col">10/10</div>
            <div class="col">10/10</div>
            <div class="col">10/10</div>
          </div>
        </div>
      <% end %>
    </ul>
  <% else %>
    <p class="fst-italic">En attente de vérification par un administrateur.<p>
  <% end %>
  <div class="my-5">
    <%= link_to "Ajouter une évaluation", evaluations_builder_new_path, class: "btn btn-primary text-white" %>
    <%# if @organisation.objectifs_list.present? %>
      <%# link_to "Éditer les objectifs", edit_objectifs_list_path(id: organisation.objectifs_list.id), class: "btn btn-primary" %>
    <%# else %>
      <%# link_to "Définir des objectifs", new_objectifs_list_path, class: "btn btn-secondary mx-3" %>
    <%# end %>
    <%= link_to "Générer un code d'invitation", code_invitation_path, method: :post, class: "btn btn-success" %>
  </div>

<% end %>