config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :evaluations
    resources :organisations
    get 'resultats/:evaluation_id', to: "resultats#index", as: "resultats"
    get 'code_invitation', to: "invitation_code#index"
    post 'code_invitation', to: "invitation_code#join"
    get '/evaluations_builder/new', to: 'evaluations_builder#new'
    get '/evaluations_builder/:evaluation_id/:step', to: 'evaluations_builder#show', as: 'evaluation_builder'
    get '/', to: 'dashboard#index', as: ''
    post '/evaluations_builder/:evaluation_id/:step', to: 'evaluations_builder#update'
  end
  
  devise_for :users, path: '', path_names: { sign_in: "connexion", sign_out: "deconnexion", sign_up: "inscription", edit: "compte" }

  # get "entreprises", to: "organisations#public_list"
  get 'pilier-1', to: "statistiques#pillar1"
  get 'pilier-2', to: "statistiques#pillar2"
  get 'pilier-3', to: "statistiques#pillar3"
  get 'pilier-4', to: "statistiques#pillar4"
  get 'mentions-legales', to: "home#mentions_legales"
  get 'cgu', to: 'home#cgu'
  # get 'politique-de-confidentialite', to: 'home#politique'
  get 'contact', to: "contact#index"


  root "home#index"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    @organisation = current_user.organisation
  end
end

app/views/admin/dashboard/index.html.erb
<h1>
  <% if @organisation.present? && @organisation.validation_admin %>
    <%= @organisation %>
  <% else %>
    Tableau de bord
  <% end %>
</h1>

<%= link_to 'Modifier', edit_admin_organisation_path(@organisation), class: 'btn btn-primary mt-3' if @organisation.present? %>

<% if @organisation.nil? %>
    <%= link_to "Inscrire une organisation", new_admin_organisation_path, class: "btn btn-primary" %>
    <div class="col mt-5">
      <div id="code_messages"></div>
      <%= form_with url: admin_code_invitation_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :code, "Code d'invitation:" %>
          <%= f.text_field :code, class: "form-control" %>
        </div>
        <%= f.submit "Rejoindre une organisation", class: "btn btn-primary mt-3" %>
      <% end %>
    </div>
<% else %>
  <% if @organisation.validation_admin %>
    <h2>Evaluations</h2>

    <div class="table table-striped table-hover bg-white rounded border my-5">
      <table class="table m-0">
        <thead>
          <tr>
            <th class="p-3">Année</th>
            <th class="p-3">Informations</th>
            <th class="p-3">Pilier 1</th>
            <th class="p-3">Pilier 2</th>
            <th class="p-3">Pilier 3</th>
            <th class="p-3">Pilier 4</th>
          </tr>
        </thead>
        <tbody>
          <% current_user.organisation.evaluations.active.each do |evaluation| %>
            <tr class="align-middle">
              <td class="p-3">
                <%= link_to evaluation, [:admin, evaluation], class: "text-secondary fw-bold" %> |
                <%= link_to "Voir les résultats", admin_resultats_path(evaluation_id: evaluation.id), class: "text-primary fw-bold" %>
              </td>
              <td><%= link_to "Modifier", admin_evaluation_builder_path(evaluation.id, 'informations'), class: "btn btn-outline-success btn-sm" %></td>
              <td><%= link_to "Modifier", admin_evaluation_builder_path(evaluation.id, 'pilier1'), class: "btn btn-outline-success btn-sm" %></td>
              <td><%= link_to "Modifier", admin_evaluation_builder_path(evaluation.id, 'pilier2'), class: "btn btn-outline-success btn-sm" %></td>
              <td><%= link_to "Modifier", admin_evaluation_builder_path(evaluation.id, 'pilier3'), class: "btn btn-outline-success btn-sm" %></td>
              <td><%= link_to "Modifier", admin_evaluation_builder_path(evaluation.id, 'pilier4'), class: "btn btn-outline-success btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  <% else %>
    <p class="fst-italic">En attente de vérification par un administrateur.<p>
  <% end %>

    <%= link_to "Ajouter une évaluation", admin_evaluations_builder_new_path, class: "btn btn-primary text-white mb-5 me-3" %>
    <%= link_to "Générer un code d'invitation", admin_code_invitation_path, method: :post, class: "btn btn-success mb-5" %>

<% end %>