config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :evaluations
    resources :organisations
    get 'resultats/:evaluation_id', to: "resultats#index", as: "resultats"
    get 'code_invitation', to: "invitation_code#index"
    post 'code_invitation', to: "invitation_code#join"
    get '/evaluations_builder/new', to: 'evaluations_builder#new'
    get '/evaluations_builder/:evaluation_id/:step', to: 'evaluations_builder#show', as: 'evaluation_builder'
    get '/', to: 'dashboard#index', as: ''
    post '/evaluations_builder/:evaluation_id/:step', to: 'evaluations_builder#update'
  end
  
  devise_for :users, path: '', path_names: { sign_in: "connexion", sign_out: "deconnexion", sign_up: "inscription", edit: "compte" }

  # get "entreprises", to: "organisations#public_list"
  get 'pilier-1', to: "statistiques#pillar1"
  get 'pilier-2', to: "statistiques#pillar2"
  get 'pilier-3', to: "statistiques#pillar3"
  get 'pilier-4', to: "statistiques#pillar4"
  get 'mentions-legales', to: "home#mentions_legales"
  get 'cgu', to: 'home#cgu'
  # get 'politique-de-confidentialite', to: 'home#politique'
  get 'contact', to: "contact#index"


  root "home#index"
end

app/models/objectifs_list.rb
# == Schema Information
#
# Table name: objectifs_lists
#
#  id              :bigint           not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organisation_id :bigint
#
# Indexes
#
#  index_objectifs_lists_on_organisation_id  (organisation_id)
#
class ObjectifsList < ApplicationRecord
  belongs_to :organisation
  has_one :state, dependent: :destroy

  accepts_nested_attributes_for :state
end

app/views/admin/objectifs_lists/_form.html.erb
<% disable = "disabled" unless !defined?(disabled) || disabled != true %>
<%= simple_form_for @objectifs_list do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="formul d-flex flex-sm-row flex-column justify-content-around align-items-center bg-blue pt-0 pb-0 pt-sm-4 pb-sm-4 mt-0 mt-sm-5">
    <span class="d-none d-sm-flex m-4 col-1"><%= image_tag '1.svg', alt: 'numéro 1' %></span>
    <h2 class="m-4 white">Partage du pouvoir et des décisions</h2>
  </div>

  <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-5 shadow">
    <h3 class="text-primary">Composition de la gouvernance</h3>
  </div>

  <%= f.association :state do |il| %>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">

      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <%# <legend class="w-auto">Pilier 1 : Partage du pouvoir et des décisions</legend> %>
        <div class="col-12 col-sm-5">
          <%= il.input :pouvoir_gouvernance_part_salaries_associes %>
          <%= il.input :pouvoir_gouvernance_taux_societariat_femmes %>
          <%= il.input :pouvoir_gouvernance_taux_droits_vote_salaries %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1">
          <%= il.input :pouvoir_gouvernance_part_salaries_conseil %>
          <%= il.input :pouvoir_gouvernance_part_femmes_conseil %>
        </div>
        <div class="col-12 col-sm-10 me-auto ms-auto list-diversite">
          <%= il.input :pouvoir_gouvernance_diversite_categories, as: :check_boxes, collection: ['Salariés', 'Investisseurs', 'Fournisseurs', 'Sous-traitants', 'Clients', 'Experts', 'Syndicats', 'Pouvoirs publics', 'Associations', 'Grand public', 'Autres'], include_hidden: false %>
        </div>
      </fieldset>
    </div>

    <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-4 mt-sm-5 shadow">
      <h3 class="text-primary">Mise en place des conditions du bon exercice de la démocratie</h3>
    </div>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">
      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <div class="col-12 col-sm-5">
          <%= il.input :pouvoir_democratie_nombre_reunions %>
          <%= il.input :pouvoir_democratie_taux_participation_formations %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1">
          <%= il.input :pouvoir_democratie_nombre_accords_signes %>
          <%= il.input :pouvoir_democratie_accords_signes %>
        </div>
      </fieldset>
    </div>

    <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-5 shadow">
      <h3 class="text-primary">Participation à la prise de décision stratégique</h3>
    </div>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">
      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <div class="col-12 col-sm-5">
          <%= il.input :pouvoir_strategique_taux_presence_assemblee %>
          <%= il.input :pouvoir_strategique_implication_partage %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1">
          <%= il.input :pouvoir_strategique_actifs_total %>
          <%= il.input :pouvoir_estimation_realite %>
        </div>
      </fieldset>
    </div>

    <div class="formul d-flex flex-sm-row flex-column justify-content-around align-items-center bg-blue pt-0 pb-0 pt-sm-4 pb-sm-4 mt-0 mt-sm-5">
      <span class="d-none d-sm-flex pt-4 pb-4 col-1 "><%= image_tag '2.svg', alt: 'numéro 2' %></span>
      <h2 class="p-4 white">Pérennité économique et partage de la valeur créée</h2>
    </div>

    <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-5 shadow">
      <h3 class="text-primary">Pérennité : création de valeur, inaliénabilité et robustesse de l'entreprise</h3>
    </div>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">

      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <div class="col-12 col-sm-5">
          <%= il.input :valeur_perennite_part_capital_salaries %>
          <%= il.input :valeur_perennite_part_resultat_reserve %>
          <%= il.input :valeur_perennite_ebe_caht %>
          <%= il.input :valeur_perennite_part_endettement %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1 col-input">
          <%= il.input :valeur_perennite_existence_reserve, as: :radio_buttons %>
          <%= il.input :valeur_perennite_reserve_impartageable, as: :radio_buttons %>
          <%= il.input :valeur_perennite_attention_questions_innovation, as: :radio_buttons %>
        </div>
      </fieldset>
    </div>

    <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-5 shadow">
      <h3 class="text-primary">Partage des richesses</h3>
    </div>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">
      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <div class="col-12 col-sm-5 col-input">
          <%= il.input :valeur_partage_part_resultat_net_actionnaires %>
          <%= il.input :valeur_partage_part_resultat_salaries %>
          <%= il.input :valeur_partage_existence_accord, as: :radio_buttons %>
          <%= il.input :valeur_partage_ecart_revenus_hauts_bas %>
          <%= il.input :valeur_partage_index_egalite_homme_femme %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1 col-input">
          <%= il.input :valeur_partage_existence_epargne_salariale, as: :radio_buttons %>
          <%= il.input :valeur_partage_existence_grille_salariale, as: :radio_buttons %>
          <%= il.input :valeur_partage_publicite_grille, as: :radio_buttons %>
          <%= il.input :valeur_estimation_realite %>
        </div>
      </fieldset>
    </div>

    <div class="formul d-flex flex-sm-row flex-column justify-content-around align-items-center bg-blue pt-0 pb-0 pt-sm-4 pb-sm-4 mt-0 mt-sm-5">
      <span class="d-none d-sm-flex pt-4 pb-4 col-1 "><%= image_tag '3.svg', alt: 'numéro 3' %></span>
      <h2 class="p-4 white">Capital humain et qualité de vie au travail</h2>
    </div>

    <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-5 shadow">
      <h3 class="text-primary">Mise en place des conditions du bon exercice de la démocratie</h3>
    </div>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">
      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <div class="col-12 col-sm-5 col-input">
          <%= il.input :qualite_qvt_enquete_qvt, as: :radio_buttons %>
          <%= il.input :qualite_qvt_taux_qvt %>
          <%= il.input :qualite_qvt_part_cdi %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1">
          <%= il.input :qualite_qvt_moyenne_anciennete %>
          <%= il.input :qualite_qvt_taux_turnover %>
          <%= il.input :qualite_qvt_taux_absenteisme %>
        </div>
      </fieldset>
    </div>

    <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-5 shadow">
      <h3 class="text-primary">Développement des compétences individuelles et collectives<br/>Émancipation des salariés</h3>
    </div>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">
      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <div class="col-12 col-sm-5">
          <%= il.input :qualite_emancipation_moyenne_heures_formation %>
          <%= il.input :qualite_emancipation_taux_budget_formation_masse_salariale %>
          <%= il.input :qualite_emancipation_taux_direction_promotion_interne %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1">
          <%= il.input :qualite_estimation_realite %>
        </div>
      </fieldset>
    </div>

    <div class="formul d-flex flex-sm-row flex-column justify-content-around align-items-center bg-blue pt-0 pb-0 pt-sm-4 pb-sm-4 mt-0 mt-sm-5">
      <span class="d-none d-sm-flex pt-4 pb-4 col-1 "><%= image_tag '4.svg', alt: 'numéro 4' %></span>
      <h2 class="p-4 white">Impact environnemental, social et territorial</h2>
    </div>

    <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-5 shadow">
      <h3 class="text-primary">Impact environnemental</h3>
    </div>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">
      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <div class="col-12 col-sm-5 col-input">
          <%= il.input :impact_environnement_audit_impact, as: :radio_buttons %>
          <%= il.input :impact_environnement_demarche_ecologique, as: :radio_buttons %>
          <%= il.input :impact_environnement_discussion_impact, as: :radio_buttons %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1">
          <%= il.input :impact_environnement_part_energies_renouvelables %>
          <%= il.input :impact_environnement_part_salaries_mobilite %>
          <p>Calculez-vous le bilan carbone ?<p>
          <div class="m-3">
            <%= il.input :impact_environnement_bilan_carbone_scope_1 %>
            <%= il.input :impact_environnement_bilan_carbone_scope_2 %>
            <%= il.input :impact_environnement_bilan_carbone_scope_3 %>
          </div>
        </div>
      </fieldset>
    </div>

    <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-5 shadow">
      <h3 class="text-primary">Impact social</h3>
    </div>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">
      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <div class="col-12 col-sm-5">
          <%= il.input :impact_social_part_activite_structures_insertion %>
          <%= il.input :impact_social_alternance_apprentissage %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1">
          <%= il.input :impact_social_part_seniors %>
          <%= il.input :impact_social_part_handicap %>
        </div>
      </fieldset>
    </div>

    <div class="col-10 col-sm-6 bg-white rounded-end border-end border-primary p-4 mt-5 shadow">
      <h3 class="text-primary">Engagement en faveur de l'écosystème et du territoire </h3>
    </div>

    <div class="w-100 pe-2 ps-2 pe-sm-5 ps-sm-5">
      <fieldset class="row flex-sm-row flex-column mb-4 m-0 m-sm-5 row-cols-2 justify-content-between" <%= disable %>>
        <div class="col-12 col-sm-5">
          <%= il.input :impact_engagement_part_resultat_missions_utiles %>
          <%= il.input :impact_engagement_part_placements_responsables %>
          <%= il.input :impact_engagement_part_impots_france %>
        </div>
        <div class="col-12 col-sm-5 offset-sm-1 col-input">
          <%= il.input :impact_engagement_demarche_ethique_fournisseurs, as: :radio_buttons %>
          <%= il.input :impact_estimation_realite %>
        </div>
      </fieldset>
    </div>
  <% end %>

  <% unless disable == "disabled" %>
    <%= f.button :submit, "Enregistrer", class: 'btn btn-primary me-auto ms-auto d-flex' %>
  <% end %>
<% end %>

app/views/admin/objectifs_lists/edit.html.erb
<div class="page-orga mx-3 mx-sm-5 mx-bg-5 mt-5 pt-2">

  <header class="me-3 me-sm-5 ms-3 ms-sm-5 p-5">
    <h1 class="h2">Éditer les objectifs</h1>
  </header>

  <div class="d-flex align-items-center justify-content-start me-3 me-sm-5 ms-3 ms-sm-5 pe-5 ps-5 pb-5">
    <% if current_user.is_super_admin %>
      <%= link_to "Back to evaluations", objectifs_lists_path, class: "btn rounded light pt-1 pb-1 pe-3 ps-3 btn-primary me-3" %>
    <% else %>
      <%= link_to "Retourner au dashboard", admin_path, class: "btn rounded light pt-1 pb-1 pe-3 ps-3 btn-secondary" %>
    <% end %>
  </div>

  <%= render "form", objectifs_list: @objectifs_list %>
    <%= button_to "Supprimer ces objectifs", @objectifs_list, method: :delete, class: "btn rounded white pt-1 pb-1 pe-3 ps-3 btn-danger", form: { data: { turbo_confirm: "Êtes-vous sûr de vouloir supprimer vos objectifs ?" } } %>

</div>

app/views/admin/objectifs_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="h2">Listes d'objectifs</h1>

<div id="objectifs_lists">
  <% @objectifs_lists.each do |objectifs_list| %>
    <%= render objectifs_list %>
    <p>
      <%= link_to "Show this objectifs_list", objectifs_list %>
    </p>
  <% end %>
</div>

<%= link_to "New objectifs_list", new_objectifs_list_path %>

app/views/admin/objectifs_lists/new.html.erb
<div class="page-orga mt-5 mt-sm-0 pt-5 pt-sm-0">

  <header class="me-3 me-sm-5 ms-3 ms-sm-5 p-5">
    <h1 class="h2">Définir les objectifs</h1>
  </header>

  <% if current_user.is_super_admin? %>
    <div class="d-flex align-items-center justify-content-start me-3 me-sm-5 ms-3 ms-sm-5 pe-5 ps-5 pb-5">
      <%= link_to "Back to objectifs_lists", objectifs_lists_path, class: "btn rounded light pt-1 pb-1 pe-3 ps-3 btn-primary" %>
    </div>
  <% end %>

  <%= render "form", objectifs_list: @objectifs_list %>

  <br>

</div>

app/views/admin/objectifs_lists/show.html.erb
<div class="page-orga show mt-5 mt-sm-0 pt-5 pt-sm-0">

  <header class="me-3 me-sm-5 ms-3 ms-sm-5 p-5">
    <h1 class="h2">Objectifs</h1>
  </header>

  <div class="d-flex flex-sm-row flex-column align-items-center justify-content-between me-3 me-sm-5 ms-3 ms-sm-5 pe-5 ps-5 pb-5">

    <div>
      <%= link_to "Edit this objectifs_list", edit_objectifs_list_path(@objectifs_list), class: "btn btn-primary me-3" %>
      <% if current_user.is_super_admin %>
        <%= link_to "Back to objectifs_lists", objectifs_lists_path, class: "btn btn-secondary me-3" %>
      <% else %>
        <%= link_to "Retourner au dashboard", admin_path, class: "btn btn-secondary me-3" %>
      <% end %>
    </div>
  </div>

  <%= render "form", objectifs_list: @objectifs_list, disabled: true %>
  <%= button_to "Supprimer ces objectifs", @objectifs_list, method: :delete, class: "btn rounded white pt-1 pb-1 pe-3 ps-3 btn-danger", form: { data: { turbo_confirm: "Êtes-vous sûr de vouloir supprimer vos objectifs ?" } } %>

</div>